config/routes.rb
Rails.application.routes.draw do
  get 'experiments/page1'

  get 'experiments/page2'

  get 'experiments/page3'

  get 'pages/batman'
  get 'pages/superman'
  get 'pages/batman-vs-superman', to: "pages#batman_vs_superman"
  post	'pages/save_batmen'
  post  'pages/save_superman'
  root 'pages#batman-vs-superman' 	
  get 	'vendor/assets/imgs'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/votos_batman.rb
class VotosBatman < ApplicationRecord
end

app/models/votos_superman.rb
class VotosSuperman < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/experiments_controller.rb
class ExperimentsController < ApplicationController
  def page1
  end

  def page2
  end

  def page3
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def batman
  end
  def superman

  end
  def batman_vs_superman

  end
  def save_superman
  	pages_save_superman.create(name: params[:name], email: params[:email])
  	redirect_to pages_x_path, notice: "El usuario ha sido guardado"
  end
  def save_batmen
  	pages_save_batmen.create(name: params[:name], email: params[:email])
  	redirect_to pages_x_path, notice: "El usuario ha sido guardado"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/experiments_helper.rb
module ExperimentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/experiments/page1.html.erb
<div>
	<%= image_tag 'photo.jpg'%>
</div>

app/views/experiments/page2.html.erb
<h1>Experiments#page2</h1>
<p>Find me in app/views/experiments/page2.html.erb</p>

app/views/experiments/page3.html.erb
<h1>Experiments#page3</h1>
<p>Find me in app/views/experiments/page3.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Superheroes</title>
    <%= csrf_meta_tags %>
    <!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/batman-vs-superman.html.erb
<div class="row">
  <div class="col-md-6">
  	<div class="batman">
  		<img src="<%= asset_path 'Batman.jpg' %> " class="img-responsive" alt="Responsive image">
      <% link_to "Batman",pages_batman_path%>
      <form class="form-inline" method="POST" action="<%= pages_save_batmen_path %>" >
        <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
      <div class="form-group">
        <label for="exampleInputName2">Name</label>
        <input type="text" class="form-control" id="exampleInputName2" placeholder="Jane Doe">
      </div>
      <div class="form-group">
        <label for="exampleInputEmail2">Email</label>
        <input type="email" class="form-control" id="exampleInputEmail2" placeholder="correo@correo.com">
      </div>
      <button type="submit" class="btn btn-default">VOTAR</button>
    </form>
  	</div>
  </div>
  <div class="col-md-6">
  	<div class="superman">
  		<img src="<%= asset_path 'SupermanRoss.png' %> " class="img-responsive" alt="Responsive image">
      <%link_to "Superman",pages_superman_path%>
    <form class="form-inline" method="POST" action="<%= pages_save_superman_path %>">
      <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
      <div class="form-group">
        <label for="exampleInputName2">Name</label>
        <input type="text" name= class="form-control" id="exampleInputName2" placeholder="Jane Doe">
      </div>
      <div class="form-group">
        <label for="exampleInputEmail2">Email</label>
        <input type="email" class="form-control" id="exampleInputEmail2" name ="email" placeholder="correo@correo.com">
      </div>
      <button type="submit"  name= "enviar" value="enviar"class="btn btn-default">VOTAR</button>
    </form>
  	</div>
  </div>
</div>

app/views/pages/batman.html.erb
<div>

	<div class="jumbotron">
	
	 	<h1> "I am Batman"</h1>

	</div>
	
</div>

app/views/pages/superman.html.erb
<div class="superman">
	<div class="jumbotron">
		<h1> "This looks like a job for
			Superman"</h1>
	</div>
</div>